asc = {
	'c-Core_Force': {'require': {}, 'complete': {'Force': 1}},
	'c-Core_Entropy': {'require': {}, 'complete': {'Entropy': 1}},
	'c-Core_Form': {'require': {}, 'complete': {'Form': 1}},
	'c-Core_Inertia': {'require': {}, 'complete': {'Inertia': 1}},
	'c-Core_Life': {'require': {}, 'complete': {'Life': 1}},
	'c-The_Core': {'require': {'Force': 1, 'Life': 1, 'Form': 1, 'Inertia': 1, 'Entropy': 1}, 'complete': {'Force': 1, 'Life': 1, 'Form': 1, 'Inertia': 1, 'Entropy': 1}},
	'c-The_Falcon': {'require': {'Force': 1}, 'complete': {'Force': 3, 'Life': 2}},
	'c-The_Hatchet': {'require': {'Force': 1}, 'complete': {'Force': 3, 'Entropy': 2}},
	'c-The_Hornet': {'require': {'Force': 1}, 'complete': {'Force': 3, 'Life': 1}},
	'c-The_Serpent': {'require': {'Force': 1}, 'complete': {'Force': 3, 'Entropy': 1}},
	'c-The_Arcanist': {'require': {'Force': 5, 'Life': 1}, 'complete': {'Force': 3}},
	'c-The_Archer': {'require': {'Force': 3, 'Entropy': 2, 'Life': 1}, 'complete': {'Force': 2, 'Entropy': 1}},
	'c-The_Manticore': {'require': {'Force': 5, 'Entropy': 1}, 'complete': {'Force': 3}},
	'c-The_Scorpion': {'require': {'Force': 4, 'Entropy': 2}, 'complete': {'Force': 2}},
	'c-The_Tiger': {'require': {'Force': 4, 'Life': 2}, 'complete': {'Force': 2}},
	'c-The_Conqueror': {'require': {'Force': 7, 'Entropy': 1, 'Life': 5}, 'complete': {}},
	'c-The_Kraken': {'require': {'Force': 7, 'Entropy': 5, 'Life': 1}, 'complete': {}},
	'c-Wrath': {'require': {'Force': 8, 'Entropy': 3, 'Life': 2}, 'complete': {}},
	'c-The_Beetle': {'require': {'Life': 1}, 'complete': {'Force': 1, 'Life': 3}},
	'c-The_Hind': {'require': {'Life': 1}, 'complete': {'Force': 2, 'Life': 3}},
	'c-The_Lizard': {'require': {'Life': 1}, 'complete': {'Inertia': 1, 'Life': 3}},
	'c-The_Rabbit': {'require': {'Life': 1}, 'complete': {'Inertia': 2, 'Life': 3}},
	'c-The_Enchantress': {'require': {'Force': 1, 'Life': 5}, 'complete': {'Life': 3}},
	'c-The_Huntress': {'require': {'Force': 2, 'Inertia': 1, 'Life': 3}, 'complete': {'Force': 1, 'Life': 2}},
	'c-The_Nymph': {'require': {'Inertia': 1, 'Life': 5}, 'complete': {'Life': 3}},
	'c-Pegasus': {'require': {'Inertia': 2, 'Life': 4}, 'complete': {'Life': 2}},
	'c-The_Stag': {'require': {'Force': 2, 'Life': 4}, 'complete': {'Life': 2}},
	'c-The_Goddess': {'require': {'Force': 1, 'Inertia': 5, 'Life': 7}, 'complete': {}},
	'c-Hope': {'require': {'Force': 5, 'Inertia': 1, 'Life': 7}, 'complete': {}},
	'c-Splendor': {'require': {'Force': 3, 'Inertia': 2, 'Life': 8}, 'complete': {}},
	'c-The_Chalice': {'require': {'Form': 1}, 'complete': {'Form': 3, 'Inertia': 2}},
	'c-The_Key': {'require': {'Form': 1}, 'complete': {'Entropy': 2, 'Form': 3}},
	'c-The_Nautilus': {'require': {'Form': 1}, 'complete': {'Form': 3, 'Inertia': 1}},
	'c-The_Silkworm': {'require': {'Form': 1}, 'complete': {'Entropy': 1, 'Form': 3}},
	'c-The_Basilisk': {'require': {'Entropy': 2, 'Form': 4}, 'complete': {'Form': 2}},
	'c-Doppelganger': {'require': {'Entropy': 1, 'Form': 5}, 'complete': {'Form': 3}},
	'c-The_Dragon': {'require': {'Form': 5, 'Inertia': 1}, 'complete': {'Form': 3}},
	'c-The_Gryphon': {'require': {'Form': 4, 'Inertia': 2}, 'complete': {'Form': 2}},
	'c-Wealth': {'require': {'Entropy': 1, 'Form': 3, 'Inertia': 2}, 'complete': {'Form': 2, 'Inertia': 1}},
	'c-Cerberus': {'require': {'Entropy': 1, 'Form': 7, 'Inertia': 5}, 'complete': {}},
	'c-The_Ritual': {'require': {'Entropy': 5, 'Form': 7, 'Inertia': 1}, 'complete': {}},
	'c-Sphinx': {'require': {'Entropy': 2, 'Form': 8, 'Inertia': 3}, 'complete': {}},
	'c-The_Armadillo': {'require': {'Inertia': 1}, 'complete': {'Form': 1, 'Inertia': 3}},
	'c-The_Auroch': {'require': {'Inertia': 1}, 'complete': {'Inertia': 3, 'Life': 1}},
	'c-The_Crab': {'require': {'Inertia': 1}, 'complete': {'Inertia': 3, 'Life': 2}},
	'c-The_Guardsman': {'require': {'Inertia': 1}, 'complete': {'Form': 2, 'Inertia': 3}},
	'c-The_Casque': {'require': {'Inertia': 5, 'Life': 1}, 'complete': {'Inertia': 3}},
	'c-The_Centurion': {'require': {'Form': 1, 'Inertia': 3, 'Life': 2}, 'complete': {'Inertia': 2, 'Life': 1}},
	'c-The_Gladiator': {'require': {'Form': 3, 'Inertia': 3}, 'complete': {'Form': 1, 'Inertia': 2}},
	'c-The_Hippopotamus': {'require': {'Inertia': 4, 'Life': 2}, 'complete': {'Inertia': 2}},
	'c-The_Rhinoceros': {'require': {'Form': 2, 'Inertia': 4}, 'complete': {'Inertia': 2}},
	'c-The_Arena': {'require': {'Form': 1, 'Inertia': 7, 'Life': 5}, 'complete': {}},
	'c-Champion': {'require': {'Form': 2, 'Inertia': 8, 'Life': 3}, 'complete': {}},
	'c-Fortress': {'require': {'Form': 5, 'Inertia': 7, 'Life': 1}, 'complete': {}},
	'c-The_Crow': {'require': {'Entropy': 1}, 'complete': {'Entropy': 3, 'Form': 1}},
	'c-The_Fly': {'require': {'Entropy': 1}, 'complete': {'Entropy': 3, 'Form': 2}},
	'c-The_Vulture': {'require': {'Entropy': 1}, 'complete': {'Force': 2, 'Entropy': 3}},
	'c-Blood_Ape': {'require': {'Force': 1, 'Entropy': 3, 'Form': 2}, 'complete': {'Entropy': 2, 'Form': 1}},
	'c-Extinction': {'require': {'Force': 2, 'Entropy': 4}, 'complete': {'Entropy': 2}},
	'c-The_Imp': {'require': {'Entropy': 5, 'Form': 1}, 'complete': {'Entropy': 3}},
	'c-The_Hyena': {'require': {'Force': 1, 'Entropy': 5}, 'complete': {'Entropy': 3}},
	'c-Death': {'require': {'Force': 2, 'Entropy': 8, 'Form': 3}, 'complete': {}},
	'c-Decay': {'require': {'Force': 5, 'Entropy': 7, 'Form': 1}, 'complete': {}}
}

nodes = {
	'The_Arcanist11': {'Force': 1},
	'The_Arcanist12': {'Entropy': 1},
	'The_Arcanist13': {'Form': 1},
	'The_Arcanist14': {'Inertia': 1},
	'The_Arcanist15': {'Life': 1},
	'The_Archer11': {'Force': 1},
	'The_Archer12': {'Entropy': 1},
	'The_Archer13': {'Form': 1},
	'The_Archer14': {'Inertia': 1},
	'The_Archer15': {'Life': 1},
	'The_Manticore11': {'Force': 1},
	'The_Manticore12': {'Entropy': 1},
	'The_Manticore13': {'Form': 1},
	'The_Manticore14': {'Inertia': 1},
	'The_Manticore15': {'Life': 1},
	'The_Scorpion11': {'Force': 1},
	'The_Scorpion12': {'Entropy': 1},
	'The_Scorpion13': {'Form': 1},
	'The_Scorpion14': {'Inertia': 1},
	'The_Scorpion15': {'Life': 1},
	'The_Tiger11': {'Force': 1},
	'The_Tiger12': {'Entropy': 1},
	'The_Tiger13': {'Form': 1},
	'The_Tiger14': {'Inertia': 1},
	'The_Tiger15': {'Life': 1},
	'The_Enchantress11': {'Force': 1},
	'The_Enchantress12': {'Entropy': 1},
	'The_Enchantress13': {'Form': 1},
	'The_Enchantress14': {'Inertia': 1},
	'The_Enchantress15': {'Life': 1},
	'The_Huntress11': {'Force': 1},
	'The_Huntress12': {'Entropy': 1},
	'The_Huntress13': {'Form': 1},
	'The_Huntress14': {'Inertia': 1},
	'The_Huntress15': {'Life': 1},
	'The_Nymph11': {'Force': 1},
	'The_Nymph12': {'Entropy': 1},
	'The_Nymph13': {'Form': 1},
	'The_Nymph14': {'Inertia': 1},
	'The_Nymph15': {'Life': 1},
	'Pegasus11': {'Force': 1},
	'Pegasus12': {'Entropy': 1},
	'Pegasus13': {'Form': 1},
	'Pegasus14': {'Inertia': 1},
	'Pegasus15': {'Life': 1},
	'The_Stag11': {'Force': 1},
	'The_Stag12': {'Entropy': 1},
	'The_Stag13': {'Form': 1},
	'The_Stag14': {'Inertia': 1},
	'The_Stag15': {'Life': 1},
	'The_Basilisk11': {'Force': 1},
	'The_Basilisk12': {'Entropy': 1},
	'The_Basilisk13': {'Form': 1},
	'The_Basilisk14': {'Inertia': 1},
	'The_Basilisk15': {'Life': 1},
	'Doppelganger11': {'Force': 1},
	'Doppelganger12': {'Entropy': 1},
	'Doppelganger13': {'Form': 1},
	'Doppelganger14': {'Inertia': 1},
	'Doppelganger15': {'Life': 1},
	'The_Dragon11': {'Force': 1},
	'The_Dragon12': {'Entropy': 1},
	'The_Dragon13': {'Form': 1},
	'The_Dragon14': {'Inertia': 1},
	'The_Dragon15': {'Life': 1},
	'The_Gryphon11': {'Force': 1},
	'The_Gryphon12': {'Entropy': 1},
	'The_Gryphon13': {'Form': 1},
	'The_Gryphon14': {'Inertia': 1},
	'The_Gryphon15': {'Life': 1},
	'Wealth11': {'Force': 1},
	'Wealth12': {'Entropy': 1},
	'Wealth13': {'Form': 1},
	'Wealth14': {'Inertia': 1},
	'Wealth15': {'Life': 1},
	'The_Casque11': {'Force': 1},
	'The_Casque12': {'Entropy': 1},
	'The_Casque13': {'Form': 1},
	'The_Casque14': {'Inertia': 1},
	'The_Casque15': {'Life': 1},
	'The_Centurion11': {'Force': 1},
	'The_Centurion12': {'Entropy': 1},
	'The_Centurion13': {'Form': 1},
	'The_Centurion14': {'Inertia': 1},
	'The_Centurion15': {'Life': 1},
	'The_Gladiator11': {'Force': 1},
	'The_Gladiator12': {'Entropy': 1},
	'The_Gladiator13': {'Form': 1},
	'The_Gladiator14': {'Inertia': 1},
	'The_Gladiator15': {'Life': 1},
	'The_Hippopotamus11': {'Force': 1},
	'The_Hippopotamus12': {'Entropy': 1},
	'The_Hippopotamus13': {'Form': 1},
	'The_Hippopotamus14': {'Inertia': 1},
	'The_Hippopotamus15': {'Life': 1},
	'The_Rhinoceros11': {'Force': 1},
	'The_Rhinoceros12': {'Entropy': 1},
	'The_Rhinoceros13': {'Form': 1},
	'The_Rhinoceros14': {'Inertia': 1},
	'The_Rhinoceros15': {'Life': 1},
	'Blood_Ape11': {'Force': 1},
	'Blood_Ape12': {'Entropy': 1},
	'Blood_Ape13': {'Form': 1},
	'Blood_Ape14': {'Inertia': 1},
	'Blood_Ape15': {'Life': 1},
	'Extinction11': {'Force': 1},
	'Extinction12': {'Entropy': 1},
	'Extinction13': {'Form': 1},
	'Extinction14': {'Inertia': 1},
	'Extinction15': {'Life': 1},
	'The_Imp11': {'Force': 1},
	'The_Imp12': {'Entropy': 1},
	'The_Imp13': {'Form': 1},
	'The_Imp14': {'Inertia': 1},
	'The_Imp15': {'Life': 1},
	'The_Hyena11': {'Force': 1},
	'The_Hyena12': {'Entropy': 1},
	'The_Hyena13': {'Form': 1},
	'The_Hyena14': {'Inertia': 1},
	'The_Hyena15': {'Life': 1}
}
